//
//  PokedexListSceneConfigurator.swift
//  PokeDex
//
//  Created by Fabrizio on 6/6/19.
//  Copyright (c) 2019 Fabrizio. All rights reserved.
//
//  This file was generated by the StartApps CleanSwift Xcode Templates. V2.0
//  By Gabriel Lanata (http://StartApps.pe) with credit to http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension PokedexListSceneViewController {

    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router.passDataToNextScene(segue: segue)
    }

    override func awakeFromNib() {
        super.awakeFromNib()
        PokedexListSceneConfigurator.configure(viewController: self)
    }

    static func instantiate() -> PokedexListSceneViewController {
        let storyboard = UIStoryboard(name: "PokedexListScene", bundle: nil)
        let viewController = storyboard.instantiateInitialViewController() as! PokedexListSceneViewController
        return viewController
    }

}

class PokedexListSceneConfigurator {

    // MARK: - Configuration

    static func configure(viewController: PokedexListSceneViewController) {

        let presenter = PokedexListScenePresenter()
        presenter.viewController = viewController

        let interactor = PokedexListSceneInteractor()
        interactor.presenter = presenter

        let router = PokedexListSceneRouter()
        router.viewController = viewController
        router.interactor = interactor

        viewController.interactor = interactor
        viewController.router = router
    }

}
