//
//  PokedexListSceneInteractor.swift
//  PokeDex
//
//  Created by Fabrizio on 6/6/19.
//  Copyright (c) 2019 Fabrizio. All rights reserved.
//
//  This file was generated by the StartApps CleanSwift Xcode Templates. V2.0
//  By Gabriel Lanata (http://StartApps.pe) with credit to http://clean-swift.com
//

import Foundation

class PokedexListSceneInteractor {

    var presenter: PokedexListScenePresenter?

    // MARK: - Object variables

    // var loadAction: loadAction!

    // MARK: - Business logic

    func doFetchPokedex(request: PokedexListSceneScene.FetchPokedex.Request) {
        NetworkManager.shared.getPokemons() { result in
            self.presenter?.presentFetchPokedex(response: PokedexListSceneScene.FetchPokedex.Response(result: result))
        }
    }

}

