//
//  PokedexListSceneModels.swift
//  PokeDex
//
//  Created by Fabrizio on 6/6/19.
//  Copyright (c) 2019 Fabrizio. All rights reserved.
//
//  This file was generated by the StartApps CleanSwift Xcode Templates. V2.0
//  By Gabriel Lanata (http://StartApps.pe) with credit to http://clean-swift.com
//

import Foundation

enum PokedexListSceneScene {
    
    enum FetchPokedex {
        
        struct Request {
        }
        struct Response {
            let result: Result<[PokemonPosts],NetworkError>
        }
        struct ViewModel {
            struct DisplayedPokemon {
                let id: Int
                let name: String
                let types: [String]
                let imageURL: String
            }
            let displayedPokemons: [DisplayedPokemon]?
            let error: String?
        }
        
    }
}
