//
//  PokedexListScenePresenter.swift
//  PokeDex
//
//  Created by Fabrizio on 6/6/19.
//  Copyright (c) 2019 Fabrizio. All rights reserved.
//
//  This file was generated by the StartApps CleanSwift Xcode Templates. V2.0
//  By Gabriel Lanata (http://StartApps.pe) with credit to http://clean-swift.com
//

import Foundation

class PokedexListScenePresenter {

    weak var viewController: PokedexListSceneViewController?

    // MARK: - Presentation logic
    
    func presentFetchPokedex(response: PokedexListSceneScene.FetchPokedex.Response) {
        switch response.result {
        case .failure(let error):
            viewController?.displayFetchPokedex(viewModel: PokedexListSceneScene.FetchPokedex.ViewModel(displayedPokemons: nil, error: error.errorDescription))
        case .success(let pokemons):
            let displayedPokemons = pokemons.map({
                 PokedexListSceneScene.FetchPokedex.ViewModel.DisplayedPokemon(
                    id: $0.id,
                    name: $0.name,
                    types: $0.types.map({ $0.name }),
                    imageURL: $0.imageUrl
                )
            })
            viewController?.displayFetchPokedex(viewModel: PokedexListSceneScene.FetchPokedex.ViewModel(displayedPokemons: displayedPokemons, error: nil))
        }
    }
}
