//
//  PokedexFavouriteListPresenter.swift
//  PokeDex
//
//  Created by Fabrizio on 8/14/19.
//  Copyright (c) 2019 Fabrizio. All rights reserved.
//
//  This file was generated by the StartApps CleanSwift Xcode Templates. V2.0
//  By Gabriel Lanata (http://StartApps.pe) with credit to http://clean-swift.com
//

import Foundation

class PokedexFavouriteListPresenter {

    weak var viewController: PokedexFavouriteListViewController?

    var favouritePokemonList = [String]()
    let userDefault = UserDefaults.standard
    
    // MARK: - Presentation logic
    
    func presentFetchPokedex(response: PokedexFavouriteListScene.FechtPokemon.Response) {
        // NOTE: Format the response from the Interactor and pass the result back to the View Controller
        // NOTE: Remember to use workers if complex processing is required
        var displayedPokemons = [PokedexFavouriteListScene.FechtPokemon.ViewModel.DisplayedPokemon]()
        
        if let items = userDefault.array(forKey: "FavouritePokemon") as? [String] {
            favouritePokemonList = items
        }
        
        
        for pokemon in response.pokemonPosts{
            var types = [String]()
            for type in pokemon.types{
                let type = type.name
                types.append(type)
            }
            
            let displayedPokemon =
                PokedexFavouriteListScene.FechtPokemon.ViewModel.DisplayedPokemon(
                    id: pokemon.id,
                    name: pokemon.name,
                    types: types,
                    imageURL: pokemon.imageUrl)
            
            if favouritePokemonList.contains(pokemon.name){
                displayedPokemons.append(displayedPokemon)
            }
        }
        
        viewController?.displayFechtPokemon(viewModel: PokedexFavouriteListScene.FechtPokemon.ViewModel(displayedPokemons: displayedPokemons))
    }

}
