//
//  PokedexFavouriteListConfigurator.swift
//  PokeDex
//
//  Created by Fabrizio on 8/14/19.
//  Copyright (c) 2019 Fabrizio. All rights reserved.
//
//  This file was generated by the StartApps CleanSwift Xcode Templates. V2.0
//  By Gabriel Lanata (http://StartApps.pe) with credit to http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension PokedexFavouriteListViewController {

    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router.passDataToNextScene(segue: segue)
    }

    override func awakeFromNib() {
        super.awakeFromNib()
        PokedexFavouriteListConfigurator.configure(viewController: self)
    }

    static func instantiate() -> PokedexFavouriteListViewController {
        let storyboard = UIStoryboard(name: "PokedexFavouriteList", bundle: nil)
        let viewController = storyboard.instantiateInitialViewController() as! PokedexFavouriteListViewController
        return viewController
    }

}

class PokedexFavouriteListConfigurator {

    // MARK: - Configuration

    static func configure(viewController: PokedexFavouriteListViewController) {

        let presenter = PokedexFavouriteListPresenter()
        presenter.viewController = viewController

        let interactor = PokedexFavouriteListInteractor()
        interactor.presenter = presenter

        let router = PokedexFavouriteListRouter()
        router.viewController = viewController
        router.interactor = interactor

        viewController.interactor = interactor
        viewController.router = router
    }

}
