//
//  PokedexFavouriteListCells.swift
//  PokeDex
//
//  Created by Fabrizio on 8/14/19.
//  Copyright (c) 2019 Fabrizio. All rights reserved.
//
//  This file was generated by the StartApps CleanSwift Xcode Templates. V2.0
//  By Gabriel Lanata (http://StartApps.pe) with credit to http://clean-swift.com
//

import UIKit

class PokedexFavouriteListTableViewCell: UITableViewCell {
    
    static let identifier = "PokedexFavouriteListTableViewCell"
    
    @IBOutlet weak var pokemonView: UIImageView!
    @IBOutlet weak var detailLabel: UILabel!
    
    override func awakeFromNib() {
        super.awakeFromNib()
        // Configure cell initial settings
    }
    
    var displayedSomething: PokedexFavouriteListScene.FechtPokemon.ViewModel.DisplayedPokemon! {
        didSet {
            // Configure cell from object
            // iconImageView.image = displayedSomething.image
            // titleLabel.text = displayedSomething.title
            // contentLabel.text = displayedSomething.content
        }
    }
    
}
