//
//  PokedexFavouriteListInteractor.swift
//  PokeDex
//
//  Created by Fabrizio on 8/14/19.
//  Copyright (c) 2019 Fabrizio. All rights reserved.
//
//  This file was generated by the StartApps CleanSwift Xcode Templates. V2.0
//  By Gabriel Lanata (http://StartApps.pe) with credit to http://clean-swift.com
//

import Foundation

class PokedexFavouriteListInteractor {

    var presenter: PokedexFavouriteListPresenter?

    // MARK: - Object variables

    // var loadAction: loadAction!
    
    var pokemons: [PokemonPosts]?
    let pokedexStringURL = "https://api.myjson.com/bins/1gs2ua"

    // MARK: - Business logic

    func doFechtPokemon(request: PokedexFavouriteListScene.FechtPokemon.Request) {
        if request.forced {
            guard let url = URL(string: pokedexStringURL) else {return}
            let task = URLSession.shared.dataTask(with: url) { (data, response, error) in
                guard let dataResponse = data,
                    error == nil else {
                        print(error?.localizedDescription ?? "Response Error")
                        return }
                
                guard let pokemon = try? JSONDecoder().decode([PokemonPosts].self, from: dataResponse) else  {
                    print("Error decoding JSON")
                    return }
                self.pokemons = pokemon
                DispatchQueue.main.async {
                    self.presenter?.presentFetchPokedex(response: PokedexFavouriteListScene.FechtPokemon.Response(pokemonPosts: pokemon))
                }
            }
            task.resume()
        } else {
            guard let pokemons = pokemons else { return }
            self.presenter?.presentFetchPokedex(response: PokedexFavouriteListScene.FechtPokemon.Response(pokemonPosts: pokemons))
        }
        
    }
}
