//
//  PokedexDetailViewControllerPresenter.swift
//  PokeDex
//
//  Created by Fabrizio on 6/6/19.
//  Copyright (c) 2019 Fabrizio. All rights reserved.
//
//  This file was generated by the StartApps CleanSwift Xcode Templates. V2.0
//  By Gabriel Lanata (http://StartApps.pe) with credit to http://clean-swift.com
//

import Foundation

class PokedexDetailViewControllerPresenter {

    weak var viewController: PokedexDetailViewControllerViewController?

    // MARK: - Presentation logic
    
    func presentFetchPokemon(response: PokedexDetailViewControllerScene.FetchPokemon.Response) {
        // NOTE: Format the response from the Interactor and pass the result back to the View Controller
        // NOTE: Remember to use workers if complex processing is required

        viewController?.displayFetchPokemon(viewModel: PokedexDetailViewControllerScene.FetchPokemon.ViewModel(displayedPokemons: response.pokemonPost))
    }
}
